name: Deploy Github Pages

on:
  push:
    branches:
      - 'master'
      - '!beta' # only deploy the website on "master"
      - '!gh-pages'
    paths: # only run this deploy if an file in the following directories are changed
      - 'docs/**'
      - 'website/**'
  release:
    types: [created]

permissions:
  contents: read

jobs:
  website:
    permissions:
      contents: write  # for JamesIves/github-pages-deploy-action to push changes in repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install & Build
        run: node scripts/ghPagesDeploy.js
